### ISSUE TITLE
No credit

### ISSUE THREAD

**Issue by ExoticNx** [x0Z3ro0x/npcdrugsales#2]
This is my script copied word for word I would like some credits.

https://github.com/ExoticNx/esx_sell_master

**Comment by x0Z3ro0x** [comment]
Take your bullshit elsewhere. Credit was already given from the source that I got this from. If you have an issue with that, take it up with them not me.

**Comment by x0Z3ro0x** [comment]
Already tried this nonsense bullshit once here:

https://forum.fivem.net/t/release-drugs-to-npcs-esx/89431/177

Proved then beyond a doubt that I received this resource from Ferreira312. Went out of my way to talk with you and prove where I got this script from and why the credit shows Ferreira312. So I'll tell you yet again, Im not going to play who's script this is as Idgaf. I got this script from Ferreira312 and asked permission from them to use it, and thus the credit goes to him.

**Comment by ExoticNx** [comment]
you a pussy don't even cant find his resource for one. Second, then he copied me and you should give credit to me but whatever makes the community more toxic this is why people don't release scripts.

**Comment by x0Z3ro0x** [comment]
Yeah im the pussy. You must be a brain dead moron because you clearly can't read. More like YOU trying to steal Ferreira312's scripts. I didn't have to do shit. I could have easily ignored your punk ass the first time around. I didn't. I showed you personal email's giving ME permission to use this script. 

So I'll say it again because clearly you are to mental to read basic English. YOU aren't the owner of this script. Ferreira312 is. Thus credit goes to them you ignorant fuck. You can't claim I stole shit when credits are already in place or is that to hard for your small brain to understand?

If you have a problem then take it up with the person who GAVE ME permission to use this you fucking moron. Because some random chomo like you crying like a bitch after I proved the source the first time doesn't mean shit to me. Now pull the dick from your ass and start using your brain or don't bother posting with your nonsense.

**Comment by x0Z3ro0x** [comment]
Proved this clown wrong on the forums because his punk ass tried it once already. Clearly he liked abuse cuz the dumb cunt tries it again lmfao. Like the emails I had went away in the 4 months he hid under a rock. They still here you dumb fuck:

https://imgur.com/EIPROgZ
