### ISSUE TITLE
facts gay boi

### ISSUE THREAD

**Issue by ExoticNx** [x0Z3ro0x/npcdrugsales#3]
oh just so you can see even the person who you got it from forked it from mine you monkey.

![image](https://user-images.githubusercontent.com/23269823/56620817-140cb400-65df-11e9-968d-5baee582f0a0.png)

Your welcome for the script.

**Comment by x0Z3ro0x** [comment]
Another example of this cunt being to stupid to read. But since I love watching you dance like the good little monkey you are:

> Is wasn't until recent Ferreira312 forked YOUR sell master nonsense. This is a fork of Ferreira312's ESX_Drugsales not sell master.

Source - https://github.com/x0Z3ro0x/npcdrugsales/issues/2

Match that with my personal emails to confirm the Replies are in fact from Ferreira312's resp which is CLEARLY labeled ESX_Drugsales and you once again see where I got this from. But hey as long as you don't mind making a fool of yourself, I don't mind either.

Source - https://imgur.com/EIPROgZ

**Comment by x0Z3ro0x** [comment]
Just a sad cry for attention from a never was. To stupid to put 2 and 2 together and see that I did in fact get this from Ferreira312, and thanks to Vito it was fixed up and put back into working condition AND released for the rest of the world with clear credit telling everyone where the plugin came from and who helped fix it.

So what's the matter Exotic?? Ferreira312 had this script on esx for MONTHS and not one word from you about how this is yours?? But the second someone shows it loves, WITH permission, and releases it WITH permission, now all of a sudden it's yours and blah blah blah.

You sound like the broke ass family member that just realized their cousin is rich and now you want a hand out. So let me put it to your punk ass like this. Idk you, idgaf about you, and you were never in the picture when any of this was made. So you showing up now randomly, just looks like the pathetic attempt it is.

So get it through that walnut size brain of yours. I cloned this from Ferreira312's repository not yours. I emailed Ferreira312 for permission not you. But more than that I've made it pretty damn clear I have proof of all that. So take your issues to Ferreira312, and fuck off with your nonsense. You are nothing more than a random who tried disrespecting my image only to be proved wrong. Guess if you wanted to be heard out you shoulda learned some common fucking curtsy.
